---

version: 2

updates:
  - package-ecosystem: npm
    open-pull-requests-limit: 10
    schedule:
      interval: monthly
      time: '00:00'
    reviewers:
      - btkostner
    assignees:
      - btkostner
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
