name = "btkostner-io-development"
workers_dev = true
compatibility_date = "2022-04-07"
main = ".output/server/index.mjs"

[site]
bucket = ".output/public"

[build]
command = ""

[env.production]
name = "btkostner-io-production"
route = "btkostner.io/*"
