name = "btkostner-io-development"

compatibility_date = "2025-08-01"
compatibility_flags = ["nodejs_compat", "no_nodejs_compat_v2"]
main = ".output/server/index.mjs"
workers_dev = true

[assets]
binding = "ASSETS"
directory = ".output/public"

[build]
command = ""

[[d1_databases]]
binding = "DB"
database_name = "btkostner-io-development"
database_id = "edce0d49-15a6-4d59-9e96-39ab9bc92d3f"

[env.production]
name = "btkostner-io-production"
route = "btkostner.io/*"

[[env.production.d1_databases]]
binding = "DB"
database_name = "btkostner-io-production"
database_id = "be4b01b7-a1a7-486c-b182-6c37f3ad489b"
