---
name: CI

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - main

concurrency:
  group: CI ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: node
        name: Install (Node)
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version-file: .tool-versions

      - id: cache
        name: Cache
        uses: actions/cache@v4
        with:
          key: ${{ steps.node.outputs.node-version }}-${{ hashFiles('package-lock.json') }}
          path: node_modules

      - if: steps.cache.outputs.cache-hit != 'true'
        name: Install (Npm)
        run: npm ci --prefer-offline --no-audit --no-fund

      - name: Build
        run: npm run build
        env:
          NITRO_PRESET: cloudflare

  Format:
    name: Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: node
        name: Install (Node)
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version-file: .tool-versions

      - id: cache
        name: Cache
        uses: actions/cache@v4
        with:
          key: ${{ steps.node.outputs.node-version }}-${{ hashFiles('package-lock.json') }}
          path: node_modules

      - if: steps.cache.outputs.cache-hit != 'true'
        name: Install (Npm)
        run: npm ci --prefer-offline --no-audit --no-fund

      - name: Format
        run: npm run format -- --check

  Lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: node
        name: Install (Node)
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version-file: .tool-versions

      - id: cache
        name: Cache
        uses: actions/cache@v4
        with:
          key: ${{ steps.node.outputs.node-version }}-${{ hashFiles('package-lock.json') }}
          path: node_modules

      - if: steps.cache.outputs.cache-hit != 'true'
        name: Install (Npm)
        run: npm ci --prefer-offline --no-audit --no-fund

      - name: Prepare
        run: npx nuxi prepare

      - name: Lint
        run: npm run lint
