---
name: Deploy

on:
  push:
    branches:
      - main

concurrency:
  group: Production
  cancel-in-progress: true

jobs:
  Publish:
    name: Publish
    runs-on: ubuntu-latest

    environment:
      name: Production
      url: https://btkostner.io

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: node
        name: Install (Node)
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version-file: .tool-versions

      - id: cache
        name: Cache
        uses: actions/cache@v4
        with:
          key: ${{ steps.node.outputs.node-version }}-${{ hashFiles('package-lock.json') }}
          path: node_modules

      - if: steps.cache.outputs.cache-hit != 'true'
        name: Install (Npm)
        run: npm ci --prefer-offline --no-audit --no-fund

      - name: Build
        run: npm run build
        env:
          NITRO_PRESET: cloudflare

      - name: Publish
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          environment: production
