---

name: Deploy

on:
  push:
    branches:
      - main

env:
  FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}

jobs:
  GitHub_Pages:
    name: GitHub Pages
    runs-on: ubuntu-latest

    steps:
      - name: Cancel
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup (Node)
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install (Npm)
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: btkostner.io

  Cloudflare_Purge:
    name: Cloudflare (Purge)
    runs-on: ubuntu-latest

    needs:
      - GitHub_Pages

    steps:
      - name: Purge
        run: |
          curl -X DELETE \
            https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE }}/purge_cache \
            -H 'Content-Type: application/json' \
            -H 'Authorization: Bearer ${{ secrets.CLOUDFLARE_KEY }}' \
            -H 'cache-control: no-cache' \
            -d '{"purge_everything":true}'
