---
name: Preview

on:
  workflow_dispatch: {}

concurrency:
  group: Preview

jobs:
  Publish:
    name: Publish
    runs-on: ubuntu-latest

    environment:
      name: Production
      url: https://btkostner.io

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install (Node)
        uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: "16.13.0"

      - name: Cache
        id: cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: 16.13.0-${{ hashFiles('package-lock.json') }}

      - name: Install (Npm)
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci --prefer-offline --no-audit --no-fund
        env:
          FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}

      - name: Build
        run: npm run build
        env:
          FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}
          NITRO_PRESET: cloudflare

      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
