---

name: Preview

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  group: Preview PR ${{ github.event.number }}
  cancel-in-progress: true

jobs:
  GitHub_Pages:
    name: GitHub Pages
    runs-on: ubuntu-latest

    environment:
      name: Preview
      url: https://btkostner.io/pr/${{ github.event.number }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install (Node)
        uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: '16.13.0'

      - name: Cache
        id: cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: 16.13.0-${{ hashFiles('package-lock.json') }}

      - name: Install (Npm)
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install --prefer-offline --no-audit --no-fund
        env:
          FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}

      - name: Build
        run: npm run build
        env:
          DEPLOY_PATH: /pr/${{ github.event.number }}
          FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          destination_dir: ./pr/${{ github.event.number }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

---

name: Preview

on:
  pull_request:
    types:
      - closed

concurrency:
  group: Preview PR ${{ github.event.number }}
  cancel-in-progress: true

jobs:
  GitHub_Pages:
    name: GitHub Pages
    runs-on: ubuntu-latest

    steps:
      - name: Fetch
        id: fetch
        uses: octokit/request-action@v2.x
        env:
          GITHUB_TOKEN: ${{ secrets.GH_DEPLOY_KEY }}
        with:
          route: GET /repos/{owner}/{repo}/deployments
          owner: ${{ github.event.repository.owner.login }}
          repo: ${{ github.event.repository.name }}
          ref: ${{ github.event.pull_request.head.ref }}
          environment: Preview

      - name: Delete
        uses: peaceiris/actions-gh-pages@v3
        with:
          destination_dir: ./pr/${{ github.event.number }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

      - name: Destroy
        uses: octokit/request-action@v2.x
        env:
          GITHUB_TOKEN: ${{ secrets.GH_DEPLOY_KEY }}
        with:
          route: POST /repos/{owner}/{repo}/deployments/{deployment_id}/statuses
          owner: ${{ github.event.repository.owner.login }}
          repo: ${{ github.event.repository.name }}
          deployment_id: ${{ fromJson(steps.fetch.outputs.data)[0].id }}
          state: inactive
