---

name: Preview Setup

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  group: Preview PR ${{ github.event.number }}
  cancel-in-progress: true

jobs:
  GitHub_Pages:
    name: GitHub Pages
    runs-on: ubuntu-latest

    environment:
      name: Preview
      url: https://btkostner.io/pr/${{ github.event.number }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install (Node)
        uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: '16.13.0'

      - name: Cache
        id: cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: 16.13.0-${{ hashFiles('package-lock.json') }}

      - name: Install (Npm)
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci --prefer-offline --no-audit --no-fund
        env:
          FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}

      - name: Build
        run: npm run build
        env:
          DEPLOY_PATH: /pr/${{ github.event.number }}
          FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          destination_dir: ./pr/${{ github.event.number }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
